# render.yaml
services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URL
        value: your-mongodb-uri-here
